### ISSUE TITLE
Paimon.moe exported Excel file has different mimetype than it expects while importing the files

### ISSUE THREAD

**Issue by 5310** [MadeBaruna/paimon-moe#92]
In the process of trying to convert my Wishes from Genshin-wishes into Paimon.moe I noticed that Paimon.moe can't seem to import its _own_ exported Excel files, due to it restricting imports to a different mimetype than it exports to.

# Environment Tested

1. Chrome 91, Manjaro Linux
2. Chrome 91, Android 11
2. Chrome 90, Android 10

# Steps to Reproduce

The following is done on a fresh account for reproducibility.

1. Auto-import some wishes into Paimon.moe
2. Export all the wishes from settings
3. Try to import that same .xlsx into Paimon.moe by either dragging an exported file back into the import interface, or selecting the file manually

# Expected results

The exported data will be imported into the active Paimon.moe account.

# Encountered Issue

As soon as _any_ file is dropped in or selected Paimon.moe pops up a toast saying `invalid Excel file`. This includes perfectly valid readable Excel files exported out of Paimon.moe merely seconds ago.

# Additional Information

It seems the Excel file exported from Paimon.moe has the mimetype marked as `application/wps-office.xlsx` instead of either `application/vnd.ms-excel` or `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` the latter of which the [code actually checks for](https://github.com/MadeBaruna/paimon-moe/blob/fca2ce5038c96838e270069618477411db658891/src/routes/wish/_excelImport.svelte#L303). The file actually exported by Paimon.moe and ExcelJS is most definitely not set to the OpenXML mimetype at all, which might an issue with ExcelJS, which I am not familiar with.

On this note, may I partly second issue #81 in that the exported file could be far simpler and not to mention smaller than an Excel file with a bunch of derived values and embedded images? A simple CSV would be so much less hassle, and Excel can open them anyway.

**Comment by MadeBaruna** [comment]
thanks, I think file downloaded on linux has different mime type, will fix this later

**Comment by 5310** [comment]
I downloaded some of the exports on Android as well, but I guess that's the same thing either way. Can't really test on Windows I'm afraid. Thanks for looking into it :]

**Comment by TheJali7** [comment]
This just an update that I was able to import my genshin-wishes to paimon.moe just today (Chrome Android 95)

**Comment by MadeBaruna** [comment]
Fixed on https://github.com/MadeBaruna/paimon-moe/commit/712d71cac371464501a0cdfa62747e70985e0294 *I hope*

**Comment by Insirus** [comment]
I still can't even import paimon.moe's own excel. "Invalid excel file". I added a few test wishes on the site and this is the file I got exported on Windows 10, Chrome.

[paimonmoe_wish_history.xlsx](https://github.com/MadeBaruna/paimon-moe/files/7482361/paimonmoe_wish_history.xlsx)

And my old xlsx was apparently TakaGG one, it still can't be imported either.

**Comment by MadeBaruna** [comment]
@Insirus did you use manual input? Because there is unknown item name on the standard banner. This is a different issue, for now you can delete the unknown stuff

**Comment by Insirus** [comment]
> @Insirus did you use manual input? Because there is unknown item name on the standard banner. This is a different issue, for now you can delete the unknown stuff

Nevermind, I just checked and weirdly enough it was something with my browser :) Everything works fine in another one and gives "unknown type" error if there's unknown items.
